# Generated by Django 3.0.5 on 2020-08-22 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMAQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='EMAResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EMASession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_sent', models.PositiveSmallIntegerField(default=1)),
                ('questions_answered', models.PositiveSmallIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_question_sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ema.EMAQuestions')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ema.EMASession')),
            ],
        ),
    ]
