# Generated by Django 3.0.5 on 2020-08-21 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMAQuestions',
            fields=[
                ('unique_id', models.IntegerField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='EMAResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.PositiveSmallIntegerField()),
                ('question', models.ManyToManyField(related_name='ema_responses', to='ema.EMAQuestions')),
            ],
        ),
        migrations.CreateModel(
            name='EMASession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField()),
                ('started_at', models.DateTimeField()),
                ('session_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ema.EMASession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='emaquestion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='questionresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='EMAQuestion',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionResponse',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.AddField(
            model_name='emaresponse',
            name='session_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ema_responses', to='ema.EMASession'),
        ),
        migrations.AddField(
            model_name='emaresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
