# Generated by Django 3.0.5 on 2020-08-22 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ema', '0002_auto_20200822_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaresponse',
            name='session',
        ),
        migrations.RemoveField(
            model_name='emaresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emasession',
            name='first_question',
        ),
        migrations.RemoveField(
            model_name='sessionstate',
            name='last_question_sent',
        ),
        migrations.RemoveField(
            model_name='sessionstate',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='sessionstate',
            name='messages_sent',
        ),
        migrations.RemoveField(
            model_name='sessionstate',
            name='questions_answered',
        ),
        migrations.AddField(
            model_name='emaresponse',
            name='state',
            field=models.ForeignKey(default='state', on_delete=django.db.models.deletion.CASCADE, related_name='ema_responses', to='ema.SessionState'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='emaresponse',
            name='question',
        ),
        migrations.AddField(
            model_name='emaresponse',
            name='question',
            field=models.ForeignKey(default='question', on_delete=django.db.models.deletion.CASCADE, related_name='ema_responses', to='ema.EMAQuestions'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='QuestionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_asked', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ema.EMAQuestions')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ema.SessionState')),
            ],
        ),
        migrations.AddField(
            model_name='sessionstate',
            name='questions_asked',
            field=models.ManyToManyField(through='ema.QuestionHistory', to='ema.EMAQuestions'),
        ),
    ]
