# Generated by Django 3.0.5 on 2020-11-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ema", "0002_studymeta"),
    ]

    operations = [migrations.RenameModel("EMAQuestions", "EMAQuestion")]
