# Generated by Django 3.0.5 on 2020-12-01 15:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ema", "0004_auto_20201105_1746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessiontime",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_times",
                to="ema.StudyMeta",
            ),
        ),
        migrations.AlterField(
            model_name="studymeta",
            name="beeps_per_day",
            field=models.PositiveIntegerField(
                verbose_name=django.core.validators.MaxValueValidator(48)
            ),
        ),
    ]
