# Generated by Django 3.0.5 on 2020-12-02 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ema', '0005_auto_20201201_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymeta',
            name='start_scheduler',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studymeta',
            name='beeps_per_day',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
