# Generated by Django 3.0.5 on 2020-08-22 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trackhistory',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_histories', to='music.UserHistory'),
        ),
        migrations.AddField(
            model_name='trackhistory',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Track'),
        ),
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(related_name='tracks', to='music.Artist'),
        ),
        migrations.AddField(
            model_name='fulluserhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
