# Generated by Django 3.0.5 on 2020-10-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulluserhistory',
            name='artist',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='fulluserhistory',
            name='track_name',
            field=models.CharField(max_length=600),
        ),
    ]
