name: Django CI

on:
  push:
    branches:
    - '**' # Runs workflow everyone time code is pushed to repo
    paths-ignore:
    - 'docs/**' # Will not run for anything pushed to docs
  pull_request:
    branches:
    # Also runs on any pull request to main or develop branches 
    - main 
    - develop

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/local.txt
    - name: Run Tests
      run: |
        pytest
